import newsDog from '../images/news-dog.jpg';

const cardsArray = [
  {
    id: 1,
    keyword: 'doggy',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    date: 'November 1, 2021',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 2,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 3,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 4,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 5,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 6,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 7,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 8,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 9,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 10,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 11,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
  {
    id: 12,
    keyword: 'doggy',
    date: 'November 1, 2021',
    title: 'Dog Rescued From Fire',
    text: 'It turns out the dog wasnt nice, and shouldnt have been saved',
    source: 'my aunt told me',
    image: 'http://www.news.com',
    link: 'http://www.news.com',
    alt: 'news doggy',
  },
];
export default cardsArray;
